### ISSUE TITLE
terser.js error from wgpu_canvas_context_get_current_texture

### ISSUE THREAD

**Issue by brendan-duncan** [juj/wasm_webgpu#16]
I got the not very helpful error `MOZ_TO_ME[node.type] is not a function` while working on updating to the current lib_webgpu.

I added a debug print statement into the terser.js from_moz function to see what was throwing it off, and saw it was a chainexpression node. Looks like terser.js doesn't support them, and the line:
`{{{ wassert('!(texture.derivedObjects?.length > 1000)'); }}}`
in wgpu_canvas_context_get_current_texture caused the error.

**Comment by juj** [comment]
Hmm, I think the issue is an old version of terser.js (or maybe wrong spec standard input flags passed to it). The rationale for using `?.` is that it shortens code size and all browsers that will support WebGPU will also support `?.`. However given that this is only an assert, code size is not important, so adjusting the code to drop this use in above commit.

**Comment by juj** [comment]
What were the Emscripten cmdline flags (build optimization flags especially) that you were running with?

**Comment by brendan-duncan** [comment]
I believe the optimization flags being passed are `-O3 -g2` for the builds I've been doing

**Comment by brendan-duncan** [comment]
It does look like an old version of terser.js being used by this version of emscripten, 3.14.1, while the latest is 5.7.1

**Comment by juj** [comment]
Are you on latest Emscripten (does this look like something that needs update in upstream Emscripten repo?) - or would updating Emscripten locally help for you?

**Comment by brendan-duncan** [comment]
Looks like the main branch of Emscripten is on 3.14.1, https://github.com/emscripten-core/emscripten/blob/main/third_party/terser/package.json
